# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "YiLi"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://yi-li.netlify.com"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "©2020 Yi Li<br/>Hosted on [GitHub](https://github.com)· Served by [Netlify](https://ucrtheory.netlify.com)"

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
  
    # FOOTER PARAMETERS
  footmark = "feynmanfooter.png"
  stacklogo = "lego.png"
  legalblurb = "All opinions expressed here are my own and do not necessarily represent those of any other agencies or groups."

  # HEADER PARAMETERS
  watermark = "Bundle3.jpg"
  
  [[params.social]]
    icon = "inspire"
    icon_pack = "ai"
    link = "http://inspirehep.net/author/profile/P.Tanedo.1"
    cv = true

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?hl=en&user=BQuJtTIAAAAJ&view_op=list_works&sortby=pubdate"
    cv = true

  [[params.social]]
    icon = "orcid"
    icon_pack = "ai"
    link = "http://orcid.org/0000-0003-4642-2199"
    cv = true

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "//github.com/fliptanedo"
    cv = true

  [[params.social]]
    icon = "arxiv"
    icon_pack = "ai"
    link = "https://arxiv.org/find/hep-ph/1/au:+Tanedo_P/0/1/0/all/0/1"
    cv = true

  [[params.social]]
    icon = "twitter"
    icon_pack = "fab"
    link = "//twitter.com/FlipTanedo"
    cv = false

  [[params.social]]
    icon = "publons"
    icon_pack = "ai"
    link = "https://publons.com/author/637273/philip-tanedo#profile"
    cv = true

  [[params.social]]
    icon = "slideshare"
    icon_pack = "fab"
    link = "https://www.slideshare.net/fliptanedo"
    cv = false

  [[params.social]]
    icon = "tree"
    icon_pack = "fas"
    link = "https://academictree.org/physics/tree.php?pid=715850"
    cv = false

  [[params.social]]
    icon = "cv"
    icon_pack = "ai"
    link = "files/Tanedo.pdf"
    cv = false

